#!/bin/bash
export OPENSHIFT_MONGODB_DB_USERNAME=admin
export OPENSHIFT_MONGODB_DB_PASSWORD=k5nDL26QPk-7
set OPENSHIFT_MONGODB_DB_HOST=localhost
set OPENSHIFT_MONGODB_DB_PORT=27017
set OPENSHIFT_APP_NAME=sc
set OPENSHIFT_NODEJS_PORT=8080
set OPENSHIFT_NODEJS_IP=localhost

